    SUBROUTINE AC.DEBIT.CARD.END.ROUTINE

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_DAS.AC.DEBIT.CARD
    $INSERT I_DAS.AC.DEBIT.CARD.NOTES
*    $INSERT I_CARD.STATUS



*-----------------------------------------------------------------------------
    THE.LIST=DAS.AC.DEBIT.CARD$CUSTOMER.CARD
    THE.ARGS='111700'
    TABLE.SUFFIX=''
    CALL DAS('AC.DEBIT.CARD',THE.LIST,THE.ARGS,TABLE.SUFFIX)
*CALL BATCH.BUILD.LIST('',THE.LIST)
    CRT THE.LIST
    INPUT DUMMY
    END
